/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somalista.h"


void
somalista_prog_1(char *host, lista *lista_arg)
{
	CLIENT *clnt;
	int  *result_1;
	void  *result_2;

#ifndef	DEBUG
	clnt = clnt_create (host, SOMALISTA_PROG, SOMALISTA_PROG, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = soma_lista_1(lista_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
		printf("Soma lista igual a %d\n", *result_1);
	}
	result_2 = imprime_lista_1(lista_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

lista *construir_lista(int argc, char *argv[]) {
    lista *head = NULL;
    lista *current = NULL;
    for (int i = 2; i < argc; i++) { // Começa em 2 para ignorar o host
        lista *novo = (lista *)malloc(sizeof(lista));
        if (novo == NULL) {
            fprintf(stderr, "Erro ao alocar memória\n");
            exit(1);
        }
        novo->num = atoi(argv[i]);
        novo->prox = NULL;
        if (head == NULL) {
            head = novo;
            current = head;
        } else {
            current->prox = novo;
            current = novo;
        }
    }
    return head;
}


int
main (int argc, char *argv[])
{
	char *host;
	lista *lista_arg;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	lista_arg = construir_lista(argc, argv);
	somalista_prog_1 (host, lista_arg);

	 // Libera a memória da lista
    lista *current = lista_arg;
    while (current != NULL) {
        lista *temp = current;
        current = current->prox;
        free(temp);
    }

    exit(0);
}
