/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMALISTA_H_RPCGEN
#define _SOMALISTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct lista {
	int num;
	struct lista *prox;
};
typedef struct lista lista;


#define SOMALISTA_PROG 0x13
#define SOMALISTA_PROG 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA_LISTA 1
extern  int * soma_lista_1(lista *, CLIENT *);
extern  int * soma_lista_1_svc(lista *, struct svc_req *);
#define IMPRIME_LISTA 2
extern  void * imprime_lista_1(lista *, CLIENT *);
extern  void * imprime_lista_1_svc(lista *, struct svc_req *);
extern int somalista_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA_LISTA 1
extern  int * soma_lista_1();
extern  int * soma_lista_1_svc();
#define IMPRIME_LISTA 2
extern  void * imprime_lista_1();
extern  void * imprime_lista_1_svc();
extern int somalista_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lista (XDR *, lista*);
extern  bool_t xdr_lista (XDR *, lista*);

#else /* K&R C */
extern bool_t xdr_lista ();
extern bool_t xdr_lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMALISTA_H_RPCGEN */
