/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


void
prog_10(char *host, int x,int y,char op)
{
	CLIENT *clnt;
	int  *result;
	operandos ops;
	

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	ops.x = x;
	ops.y = y;

	switch(op){
		case '+':
			result = add_10(&ops, clnt);
			printf("%d\n", *result);
			break;
		case '-':
			result = sub_10(&ops, clnt);
			printf("%d\n", *result);
			break;
		case '*':
			result = mult_10(&ops, clnt);
			printf("%d\n", *result);
			break;
		case '/':
			result = div_10(&ops, clnt);
			printf("%d\n", *result);
			break;
		default:
			printf("Operacao %c desconhecida\n", op);
			exit(1);
	}
	

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, op;
	int x, y;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	x = atoi(argv[2]);
	y = atoi(argv[3]);
	op = argv[4][0];
	
	prog_10 (host, x, y, op);
exit (0);
}
